// Generated by CoffeeScript 1.6.3
(function() {
  var App, FullCommentItem, Page, RightSection, pdfUrl,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    _this = this;

  console.log("run");

  pdfUrl = null;

  App = (function(_super) {
    __extends(App, _super);

    function App() {
      var am, tm,
        _this = this;
      am = new Suzaku.ApiManager;
      am.setPath("");
      tm = new Suzaku.TemplateManager;
      tm.setPath("templates/");
      tm.use("full-comment-item");
      tm.start(function(tpls) {
        window.tpls = tpls;
        return _this.start();
      });
    }

    App.prototype.start = function() {
      var p, pages, _i, _len, _ref;
      this.pages = [];
      _ref = pages = $(".page");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        this.pages.push(new Page(p));
      }
      return this.rightSection = new RightSection();
    };

    return App;

  })(Suzaku.EventEmitter);

  RightSection = (function(_super) {
    __extends(RightSection, _super);

    function RightSection() {
      var i, item, _i;
      RightSection.__super__.constructor.call(this, "#right-section");
      for (i = _i = 1; _i <= 5; i = ++_i) {
        item = new FullCommentItem();
        console.log(item);
        console.log(this.UI['comments-wrapper']);
        item.appendTo(this.UI['comments-wrapper']);
      }
    }

    return RightSection;

  })(Suzaku.Widget);

  FullCommentItem = (function(_super) {
    __extends(FullCommentItem, _super);

    function FullCommentItem(data) {
      FullCommentItem.__super__.constructor.call(this, window.tpls['full-comment-item']);
    }

    return FullCommentItem;

  })(Suzaku.Widget);

  Page = (function(_super) {
    __extends(Page, _super);

    function Page(pageContainerDom) {
      var id;
      Page.__super__.constructor.call(this, pageContainerDom);
      id = this.dom.id.replace("pageContainer", "");
      this.initInteraction();
    }

    Page.prototype.initInteraction = function() {
      var _this = this;
      this.dom.onmousedown = function() {};
      this.dom.onmouseup = function() {};
      return this.dom.onmousemove = function() {};
    };

    return Page;

  })(Suzaku.Widget);

  RunPDFViewer(pdfUrl, function() {
    return new App();
  });

}).call(this);
